export const mockDepartments = [
  {
    departmentId: 1,
    displayName: 'American Decorative Arts',
  },
  {
    departmentId: 3,
    displayName: 'Ancient Near Eastern Art',
  },
  {
    departmentId: 4,
    displayName: 'Arms and Armor',
  },
  {
    departmentId: 5,
    displayName: 'Arts of Africa, Oceania, and the Americas',
  },
  {
    departmentId: 6,
    displayName: 'Asian Art',
  },
  {
    departmentId: 7,
    displayName: 'The Cloisters',
  },
  {
    departmentId: 8,
    displayName: 'The Costume Institute',
  },
  {
    departmentId: 9,
    displayName: 'Drawings and Prints',
  },
  {
    departmentId: 10,
    displayName: 'Egyptian Art',
  },
  {
    departmentId: 11,
    displayName: 'European Paintings',
  },
  {
    departmentId: 12,
    displayName: 'European Sculpture and Decorative Arts',
  },
  {
    departmentId: 13,
    displayName: 'Greek and Roman Art',
  },
  {
    departmentId: 14,
    displayName: 'Islamic Art',
  },
  {
    departmentId: 15,
    displayName: 'The Robert Lehman Collection',
  },
  {
    departmentId: 16,
    displayName: 'The Libraries',
  },
  {
    departmentId: 17,
    displayName: 'Medieval Art',
  },
  {
    departmentId: 18,
    displayName: 'Musical Instruments',
  },
  {
    departmentId: 19,
    displayName: 'Photographs',
  },
  {
    departmentId: 21,
    displayName: 'Modern Art',
  },
] as const;

export const mockObjectInDeparment = {
  objectID: 1,
  isHighlight: false,
  accessionNumber: '1979.486.1',
  accessionYear: '1979',
  isPublicDomain: false,
  primaryImage: '',
  primaryImageSmall: '',
  additionalImages: [],
  constituents: [
    {
      constituentID: 164292,
      role: 'Maker',
      name: 'James Barton Longacre',
      constituentULAN_URL: 'http://vocab.getty.edu/page/ulan/500011409',
      constituentWikidata_URL: 'https://www.wikidata.org/wiki/Q3806459',
      gender: '',
    },
  ],
  department: 'The American Wing',
  objectName: 'Coin',
  title: 'One-dollar Liberty Head Coin',
  culture: '',
  period: '',
  dynasty: '',
  reign: '',
  portfolio: '',
  artistRole: 'Maker',
  artistPrefix: '',
  artistDisplayName: 'James Barton Longacre',
  artistDisplayBio:
    'American, Delaware County, Pennsylvania 1794–1869 Philadelphia, Pennsylvania',
  artistSuffix: '',
  artistAlphaSort: 'Longacre, James Barton',
  artistNationality: 'American',
  artistBeginDate: '1794',
  artistEndDate: '1869',
  artistGender: '',
  artistWikidata_URL: 'https://www.wikidata.org/wiki/Q3806459',
  artistULAN_URL: 'http://vocab.getty.edu/page/ulan/500011409',
  objectDate: '1853',
  objectBeginDate: 1853,
  objectEndDate: 1853,
  medium: 'Gold',
  dimensions: 'Dimensions unavailable',
  measurements: null,
  creditLine: 'Gift of Heinz L. Stoppelmann, 1979',
  geographyType: '',
  city: '',
  state: '',
  county: '',
  country: '',
  region: '',
  subregion: '',
  locale: '',
  locus: '',
  excavation: '',
  river: '',
  classification: '',
  rightsAndReproduction: '',
  linkResource: '',
  metadataDate: '2021-04-06T04:41:04.967Z',
  repository: 'Metropolitan Museum of Art, New York, NY',
  objectURL: 'https://www.metmuseum.org/art/collection/search/1',
  tags: null,
  objectWikidata_URL: '',
  isTimelineWork: false,
  GalleryNumber: '',
};

export const mockObjectList = [
  {
    objectID: 2,
    isHighlight: false,
    accessionNumber: '1980.264.5',
    accessionYear: '1980',
    isPublicDomain: false,
    primaryImage: '',
    primaryImageSmall: '',
    additionalImages: [],
    constituents: [
      {
        constituentID: 1079,
        role: 'Maker',
        name: 'Christian Gobrecht',
        constituentULAN_URL: 'http://vocab.getty.edu/page/ulan/500077295',
        constituentWikidata_URL: 'https://www.wikidata.org/wiki/Q5109648',
        gender: '',
      },
    ],
    department: 'The American Wing',
    objectName: 'Coin',
    title: 'Ten-dollar Liberty Head Coin',
    culture: '',
    period: '',
    dynasty: '',
    reign: '',
    portfolio: '',
    artistRole: 'Maker',
    artistPrefix: '',
    artistDisplayName: 'Christian Gobrecht',
    artistDisplayBio: '1785–1844',
    artistSuffix: '',
    artistAlphaSort: 'Gobrecht, Christian',
    artistNationality: '',
    artistBeginDate: '1785',
    artistEndDate: '1844',
    artistGender: '',
    artistWikidata_URL: 'https://www.wikidata.org/wiki/Q5109648',
    artistULAN_URL: 'http://vocab.getty.edu/page/ulan/500077295',
    objectDate: '1901',
    objectBeginDate: 1901,
    objectEndDate: 1901,
    medium: 'Gold',
    dimensions: 'Dimensions unavailable',
    measurements: null,
    creditLine: 'Gift of Heinz L. Stoppelmann, 1980',
    geographyType: '',
    city: '',
    state: '',
    county: '',
    country: '',
    region: '',
    subregion: '',
    locale: '',
    locus: '',
    excavation: '',
    river: '',
    classification: '',
    rightsAndReproduction: '',
    linkResource: '',
    metadataDate: '2021-04-06T04:41:04.967Z',
    repository: 'Metropolitan Museum of Art, New York, NY',
    objectURL: 'https://www.metmuseum.org/art/collection/search/2',
    tags: null,
    objectWikidata_URL: '',
    isTimelineWork: false,
    GalleryNumber: '',
  },
  {
    objectID: 1,
    isHighlight: false,
    accessionNumber: '1979.486.1',
    accessionYear: '1979',
    isPublicDomain: false,
    primaryImage: '',
    primaryImageSmall: '',
    additionalImages: [],
    constituents: [
      {
        constituentID: 164292,
        role: 'Maker',
        name: 'James Barton Longacre',
        constituentULAN_URL: 'http://vocab.getty.edu/page/ulan/500011409',
        constituentWikidata_URL: 'https://www.wikidata.org/wiki/Q3806459',
        gender: '',
      },
    ],
    department: 'The American Wing',
    objectName: 'Coin',
    title: 'One-dollar Liberty Head Coin',
    culture: '',
    period: '',
    dynasty: '',
    reign: '',
    portfolio: '',
    artistRole: 'Maker',
    artistPrefix: '',
    artistDisplayName: 'James Barton Longacre',
    artistDisplayBio:
      'American, Delaware County, Pennsylvania 1794–1869 Philadelphia, Pennsylvania',
    artistSuffix: '',
    artistAlphaSort: 'Longacre, James Barton',
    artistNationality: 'American',
    artistBeginDate: '1794',
    artistEndDate: '1869',
    artistGender: '',
    artistWikidata_URL: 'https://www.wikidata.org/wiki/Q3806459',
    artistULAN_URL: 'http://vocab.getty.edu/page/ulan/500011409',
    objectDate: '1853',
    objectBeginDate: 1853,
    objectEndDate: 1853,
    medium: 'Gold',
    dimensions: 'Dimensions unavailable',
    measurements: null,
    creditLine: 'Gift of Heinz L. Stoppelmann, 1979',
    geographyType: '',
    city: '',
    state: '',
    county: '',
    country: '',
    region: '',
    subregion: '',
    locale: '',
    locus: '',
    excavation: '',
    river: '',
    classification: '',
    rightsAndReproduction: '',
    linkResource: '',
    metadataDate: '2021-04-06T04:41:04.967Z',
    repository: 'Metropolitan Museum of Art, New York, NY',
    objectURL: 'https://www.metmuseum.org/art/collection/search/1',
    tags: null,
    objectWikidata_URL: '',
    isTimelineWork: false,
    GalleryNumber: '',
  },
  {
    objectID: 3,
    isHighlight: false,
    accessionNumber: '67.265.9',
    accessionYear: '1967',
    isPublicDomain: false,
    primaryImage: '',
    primaryImageSmall: '',
    additionalImages: [],
    constituents: null,
    department: 'The American Wing',
    objectName: 'Coin',
    title: 'Two-and-a-Half Dollar Coin',
    culture: '',
    period: '',
    dynasty: '',
    reign: '',
    portfolio: '',
    artistRole: '',
    artistPrefix: '',
    artistDisplayName: '',
    artistDisplayBio: '',
    artistSuffix: '',
    artistAlphaSort: '',
    artistNationality: '',
    artistBeginDate: '',
    artistEndDate: '',
    artistGender: '',
    artistWikidata_URL: '',
    artistULAN_URL: '',
    objectDate: '1909–27',
    objectBeginDate: 1909,
    objectEndDate: 1927,
    medium: 'Gold',
    dimensions: 'Diam. 11/16 in. (1.7 cm)',
    measurements: [
      {
        elementName: 'Other',
        elementDescription: 'Object diameter',
        elementMeasurements: { Diameter: 1.7463 },
      },
    ],
    creditLine: 'Gift of C. Ruxton Love Jr., 1967',
    geographyType: '',
    city: '',
    state: '',
    county: '',
    country: '',
    region: '',
    subregion: '',
    locale: '',
    locus: '',
    excavation: '',
    river: '',
    classification: '',
    rightsAndReproduction: '',
    linkResource: '',
    metadataDate: '2021-04-06T04:41:04.967Z',
    repository: 'Metropolitan Museum of Art, New York, NY',
    objectURL: 'https://www.metmuseum.org/art/collection/search/3',
    tags: null,
    objectWikidata_URL: '',
    isTimelineWork: false,
    GalleryNumber: '',
  },
];
